using System.Text.Json.Serialization;
using Agro;
using Agro.Testing;
using Utils.Json;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.Unspecified)]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(float[]))]
[JsonSerializable(typeof(GraphNodePayload))]
[JsonSerializable(typeof(Dictionary<string, bool>))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(Vector3Data))]
[JsonSerializable(typeof(Vector3XDZ))]
[JsonSerializable(typeof(SimulationRequest))]
[JsonSerializable(typeof(PlantRequest))]
[JsonSerializable(typeof(ObstacleRequest))]
[JsonSerializable(typeof(SpeciesSettings))]
[JsonSerializable(typeof(SpeciesSettings[]))]
[JsonSerializable(typeof(SpeciesGraphUploadEntry))]
[JsonSerializable(typeof(List<SpeciesGraphUploadEntry>))]
[JsonSerializable(typeof(BehaviorConfigUploadEntry))]
[JsonSerializable(typeof(List<BehaviorConfigUploadEntry>))]
[JsonSerializable(typeof(Dictionary<string, List<SpeciesGraphUploadEntry>>))]
[JsonSerializable(typeof(Dictionary<string, List<BehaviorConfigUploadEntry>>))]
[JsonSerializable(typeof(ExportedGraph))]
[JsonSerializable(typeof(GraphNode))]
[JsonSerializable(typeof(GraphConnection))]
[JsonSerializable(typeof(NodePosition))]
[JsonSerializable(typeof(ImportedObjData))]
[JsonSerializable(typeof(SimulationTraceHeader))]
[JsonSerializable(typeof(StepSnapshot))]
[JsonSerializable(typeof(PlantSnapshot))]
[JsonSerializable(typeof(AgentSnapshot))]
[JsonSerializable(typeof(SeedSnapshot))]
[JsonSerializable(typeof(VirtualRootsSnapshot))]
[JsonSerializable(typeof(Vector3Snapshot))]
[JsonSerializable(typeof(QuaternionSnapshot))]
[JsonSerializable(typeof(RngSnapshot))]
[JsonSerializable(typeof(FlowerSnapshot))]
[JsonSerializable(typeof(RizomeInfoSnapshot))]
[JsonSerializable(typeof(PlantSnapshot[]))]
[JsonSerializable(typeof(AgentSnapshot[]))]
internal partial class AgroJsonSerializerContext : JsonSerializerContext;
